# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "test/SRv6"
	config.vm.provider "virtualbox" do |v|
		v.cpus = 4
		v.memory = 4096
	end

	config.vm.provider "libvirt" do |v|
		v.cpus = 4
		v.memory = 4096
	end
end
